### ISSUE TITLE
”issueベースの開発”レビュー依頼

### ISSUE THREAD

**Issue by Marimuni0221** [Marimuni0221/LeafWhisper#39]

**Comment by Marimuni0221** [comment]
### 概要

### 実装予定の機能
- [ ] ユーザー登録機能
- [ ] ユーザー情報編集機能
- [ ] ログイン機能（Google認証）
- [ ] ログアウト機能
- [ ] 商品検索機能
- [ ] 商品詳細確認機能
- [ ] 日本茶専門カフェ検索機能（Google Maps APIを使用）
- [ ] 日本茶専門カフェ詳細確認機能
- [ ] SNS(X)へのシェア機能
- [ ] レビュー投稿機能
- [ ] レビュー編集機能
- [ ] お気に入り追加機能
- [ ] お気に入りリスト確認機能

### 必要なページ
- [ ] トップページ
- [ ] ログイン画面
- [ ] ユーザー会員登録画面
- [ ] 商品検索画面
- [ ] 商品詳細画面
- [ ] カフェ検索画面
- [ ] カフェ詳細画面
- [ ] マイページ
- [ ] お気に入り一覧画面
- [ ] 投稿したレビュー一覧画面
- [ ] メールアドレスリセット画面
- [ ] パスワードリセット画面
- [ ] レビュー編集画面

**Comment by shota-hope** [comment]
> レビュー依頼用のIssueが用意できたら、そのIssueのURLをコピーして提出フォームにコピーしたものを入力して提出してください。
また、作成したGitHubProjectをpublicに変更して、URLの共有もお願いします。

Projectが公開の設定になっていないのか、確認できませんでしたので上記ご確認よろしくお願いします。

**Comment by Marimuni0221** [comment]
コメントいただきありがとうございます。
再度設定を確認致しまして、おそらく現在Projectの閲覧が可能になっているかと思います。
それでは引き続きどうぞよろしくお願い申し上げます。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです！

---

以下MVP後でも良いかと思ったカードになります。
- マイページ
- お気に入り
- SNSシェア
- パスワードリセット
- Google認証

※デプロイはrails new直後に行いましょう。
